# Generated by Django 5.0.2 on 2024-06-04 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0013_powerbitoken_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('accreditations', models.ManyToManyField(to='core.accreditation')),
            ],
        ),
        migrations.CreateModel(
            name='HelpSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='helps.helpsection')),
            ],
        ),
    ]
