# Generated by Django 5.0.2 on 2024-06-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpsection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='helpsectionitem',
            name='description',
        ),
        migrations.AlterField(
            model_name='helpsectionitem',
            name='url',
            field=models.FileField(blank=True, upload_to='helps/'),
        ),
    ]
