# Generated by Django 5.0 on 2024-03-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passport_id',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
