# Generated by Django 5.0.2 on 2024-03-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('profiles', '0002_profile_passport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accreditations',
            field=models.ManyToManyField(related_name='users', to='core.accreditation'),
        ),
    ]
