# Generated by Django 5.0.2 on 2024-02-14 19:55

import core.models.international_accreditation
import core.models.national_accreditation
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("countries", "0001_initial"),
        ("media_channels", "0001_initial"),
        ("medicals", "0001_initial"),
        ("positions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=150)),
                ("color", models.CharField(max_length=150)),
                ("license_plate", models.CharField(max_length=20)),
                ("driver_name", models.CharField(max_length=150)),
                ("driver_id", models.CharField(max_length=20)),
                ("driver_phone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CommunicationEquipmentDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution_or_media", models.CharField(max_length=150)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_type", models.CharField(max_length=50)),
                ("brand", models.CharField(max_length=150)),
                ("model", models.CharField(max_length=150)),
                ("serial_number", models.CharField(max_length=150)),
                ("approximate_value", models.IntegerField()),
                (
                    "declaration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        to="core.communicationequipmentdeclaration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneralVehicleAccreditation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mission", models.TextField()),
                ("brand", models.CharField(max_length=150)),
                ("plate", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=150)),
                ("driver", models.CharField(max_length=150)),
                ("dip", models.CharField(max_length=150)),
                ("assigned", models.TextField()),
                ("distinctive", models.CharField(max_length=150)),
                ("observations", models.TextField()),
                ("signature", models.TextField()),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="general_vehicle_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InternationalAccreditation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=core.models.international_accreditation.image_filename
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("passport_id", models.CharField(max_length=150)),
                (
                    "authorization_letter",
                    models.FileField(
                        blank=True,
                        upload_to=core.models.international_accreditation.authorization_letter_filename,
                    ),
                ),
                ("institution", models.CharField(max_length=150)),
                ("address", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=150)),
                ("phone_number_2", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("birthday", models.DateField()),
                ("birthplace", models.CharField(max_length=150)),
                ("blood_group", models.CharField(blank=True, max_length=150)),
                ("blood_rh_factor", models.CharField(blank=True, max_length=150)),
                ("age", models.PositiveIntegerField(default=18)),
                ("diseases", models.TextField()),
                ("medication_1", models.CharField(max_length=200)),
                ("medication_2", models.CharField(max_length=200)),
                ("medication_3", models.CharField(max_length=200)),
                ("medication_4", models.CharField(max_length=200)),
                ("surgical", models.CharField(blank=True, max_length=150)),
                ("doctor_name", models.CharField(blank=True, max_length=100)),
                ("hotel_name", models.CharField(max_length=120)),
                ("hotel_address", models.CharField(max_length=120)),
                ("hotel_phone", models.CharField(max_length=120)),
                ("flight_arrival_date", models.DateField()),
                ("flight_arrival_time", models.TimeField()),
                ("flight_arrival_number", models.CharField(max_length=150)),
                ("flight_departure_date", models.DateField()),
                ("flight_departure_time", models.TimeField()),
                ("flight_departure_number", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            (
                                "jefe_de_delegación_oficial",
                                "Jefe de Delegación Oficial",
                            ),
                            ("delegación_oficial", "Delegación Oficial"),
                            ("protocolo", "Protocolo"),
                            ("seguridad", "Seguridad"),
                            ("personal_de_apoyo", "Personal de Apoyo"),
                            ("prensa_oficial", "Prensa Oficial"),
                            ("tripulación", "Tripulación"),
                            ("prensa_comercial", "Prensa Comercial"),
                        ],
                        max_length=150,
                    ),
                ),
                ("authorized_by", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allergies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="international_forms",
                        to="medicals.allergy",
                    ),
                ),
                (
                    "authorized_by_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="positions.position",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="international_forms",
                        to="countries.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="international_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flight_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flight_from",
                        to="countries.country",
                    ),
                ),
                (
                    "flight_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flight_to",
                        to="countries.country",
                    ),
                ),
                (
                    "immunizations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="international_forms",
                        to="medicals.immunization",
                    ),
                ),
                (
                    "media_channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="international_forms",
                        to="media_channels.mediachannel",
                    ),
                ),
                (
                    "medicals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="international_forms",
                        to="medicals.medicalhistory",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="international_forms",
                        to="positions.position",
                    ),
                ),
                (
                    "sub_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="international_forms",
                        to="positions.subposition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NationalAccreditation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=core.models.national_accreditation.image_filename
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("passport_id", models.CharField(max_length=100)),
                (
                    "authorization_letter",
                    models.FileField(
                        blank=True,
                        upload_to=core.models.national_accreditation.authorization_letter_filename,
                    ),
                ),
                ("institution", models.CharField(max_length=150)),
                ("address", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=150)),
                ("phone_number_2", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("birthday", models.DateField()),
                ("birthplace", models.CharField(max_length=250)),
                ("blood_type", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("coordinación_general", "Coordinación General"),
                            ("protocolo", "Protocolo"),
                            ("seguridad", "Seguridad"),
                            ("personal_técnico", "Personal Técnico"),
                            ("Delegación Oficial", "Delegación Oficial"),
                            ("enlace", "Enlace"),
                            ("proveedor", "Proveedor"),
                            ("comisión_de_prensa", "Comisión de Prensa"),
                            ("prensa_comercial", "Prensa Comercial"),
                        ],
                        max_length=150,
                    ),
                ),
                ("authorized_by", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="national_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "media_channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="national_forms",
                        to="media_channels.mediachannel",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="national_forms",
                        to="positions.position",
                    ),
                ),
                (
                    "sub_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="national_forms",
                        to="positions.subposition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OverflightNonCommercialAircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aircraft_type", models.CharField(max_length=150)),
                ("model", models.CharField(max_length=150)),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[("civil", "Civil"), ("military", "Militar")],
                        default="civil",
                        max_length=50,
                    ),
                ),
                ("registration", models.CharField(max_length=150)),
                ("color", models.CharField(max_length=150)),
                ("call_sign", models.CharField(max_length=150)),
                ("commander_name", models.CharField(max_length=150)),
                ("crew_members_count", models.IntegerField()),
                ("pmi_name", models.CharField(max_length=150)),
                ("passengers_count", models.IntegerField()),
                ("arrival_date", models.DateField()),
                ("departure_date", models.DateField()),
                ("overflight_info", models.TextField()),
                ("landing_info", models.TextField()),
                ("origin", models.CharField(max_length=150)),
                ("destination", models.CharField(max_length=150)),
                ("route", models.CharField(max_length=150)),
                ("ground_facilities", models.TextField()),
                ("date", models.DateField()),
                ("signature", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flight_forms",
                        to="countries.country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flight_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flight_forms",
                        to="positions.position",
                    ),
                ),
                (
                    "sub_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flight_forms",
                        to="positions.subposition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecurityWeaponAccreditation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("control_date", models.DateField()),
                ("control_time", models.TimeField()),
                ("weapon", models.CharField(max_length=150)),
                ("brand", models.CharField(max_length=150)),
                ("model", models.CharField(max_length=150)),
                ("type", models.CharField(max_length=150)),
                ("serial", models.CharField(max_length=150)),
                ("caliber", models.CharField(max_length=150)),
                ("chargers", models.IntegerField()),
                ("ammunition", models.IntegerField()),
                ("equipment_radio", models.CharField(max_length=150)),
                ("equipment_model", models.CharField(max_length=150)),
                ("equipment_type", models.CharField(max_length=150)),
                ("equipment_serial", models.CharField(max_length=150)),
                ("equipment_frequency", models.CharField(max_length=150)),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accreditation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weapons",
                        to="core.internationalaccreditation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weapon_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleAccessAirport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("responsible_info", models.CharField(max_length=150)),
                ("responsible_signatures", models.TextField()),
                ("date", models.DateField()),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="countries.country",
                    ),
                ),
                (
                    "vehicles",
                    models.ManyToManyField(
                        related_name="accreditations", to="core.vehicle"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.ManyToManyField(
                blank=True, related_name="vehicle", to="core.vehicletypes"
            ),
        ),
    ]
