# Generated by Django 5.0 on 2024-02-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nationalaccreditation',
            name='date',
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='type',
            field=models.CharField(choices=[('coordinación_general', 'Coordinación General'), ('protocolo', 'Protocolo'), ('seguridad', 'Seguridad'), ('personal_técnico', 'Personal Técnico'), ('Delegación Oficial', 'Delegación Oficial'), ('enlace', 'Enlace'), ('proveedor', 'Proveedor'), ('comisión_de_prensa', 'Comisión de Prensa'), ('prensa_comercial', 'Prensa Comercial')], max_length=150),
        ),
    ]
