# Generated by Django 5.0 on 2024-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalacreditation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
