# Generated by Django 5.0.2 on 2024-04-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon')),
                ('login_background', models.ImageField(blank=True, null=True, upload_to='site/backgrounds')),
                ('unavailable_title', models.CharField(default='Sitio en Mantenimiento', max_length=255)),
                ('unavailable_message', models.TextField(blank=True, default='Estamos realizando tareas de mantenimiento. Por favor, vuelva más tarde.')),
                ('unavailable_color', models.CharField(blank=True, default='#000000', max_length=15)),
                ('unavailable_background', models.ImageField(blank=True, null=True, upload_to='site/backgrounds')),
            ],
        ),
    ]
