# Generated by Django 5.0.1 on 2024-02-12 02:31

import core.modelos.national_accreditation
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nationalacreditation",
            name="image",
            field=models.ImageField(
                upload_to=core.modelos.national_accreditation.NationalAcreditation.create_image_path
            ),
        ),
        migrations.AlterField(
            model_name="nationalacreditation",
            name="letter_of_authorization",
            field=models.FileField(
                upload_to=core.modelos.national_accreditation.NationalAcreditation.create_image_path
            ),
        ),
    ]
