# Generated by Django 5.0 on 2024-02-14 04:09

import core.models.national_accreditation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='letter_of_authorization',
            field=models.FileField(upload_to=core.models.national_accreditation.NationalAccreditation.upload_file_name),
        ),
    ]
