# Generated by Django 5.0.2 on 2024-02-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergies', '0001_initial'),
        ('core', '0003_alter_internationalaccreditation_allergies_and_more'),
        ('immunizations', '0001_initial'),
        ('medical_histories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalaccreditation',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='international_forms', to='allergies.allergy'),
        ),
        migrations.AlterField(
            model_name='internationalaccreditation',
            name='immunizations',
            field=models.ManyToManyField(blank=True, related_name='international_forms', to='immunizations.immunization'),
        ),
        migrations.AlterField(
            model_name='internationalaccreditation',
            name='medicals',
            field=models.ManyToManyField(blank=True, related_name='international_forms', to='medical_histories.medicalhistory'),
        ),
    ]
