# Generated by Django 5.0.1 on 2024-02-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_communicationtype_weapontype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="securityaccreditation",
            name="communication_type",
        ),
        migrations.RemoveField(
            model_name="securityaccreditation",
            name="weapon_type",
        ),
        migrations.DeleteModel(
            name="CommunicationType",
        ),
        migrations.AddField(
            model_name="securityaccreditation",
            name="communication_type",
            field=models.CharField(
                choices=[("Radio", "Radio"), ("Other", "Other")],
                default="default_value",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="WeaponType",
        ),
        migrations.AddField(
            model_name="securityaccreditation",
            name="weapon_type",
            field=models.CharField(
                choices=[
                    ("Pistol", "Pistol"),
                    ("Rifle", "Rifle"),
                    ("Shotgun", "Shotgun"),
                    ("Other", "Other"),
                ],
                default="default_value",
                max_length=50,
            ),
        ),
    ]
