# Generated by Django 5.0.2 on 2024-05-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='president',
            field=models.CharField(default='Nombre del Presidente/a', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='term_date',
            field=models.DateField(default='2024-12-31'),
        ),
    ]
