# Generated by Django 5.0.2 on 2024-05-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfiguration_president_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='text_color',
            field=models.CharField(default='#FFFFFF', max_length=150),
        ),
    ]
