# Generated by Django 5.0.1 on 2024-02-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_securityaccreditation_communication_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityaccreditation",
            name="communication_type",
            field=models.CharField(
                choices=[("Radio", "Radio"), ("Other", "Other")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="securityaccreditation",
            name="weapon_type",
            field=models.CharField(
                choices=[
                    ("Pistol", "Pistol"),
                    ("Rifle", "Rifle"),
                    ("Shotgun", "Shotgun"),
                    ("Other", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
