# Generated by Django 5.0.6 on 2024-05-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_certification_text_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="login_title",
            field=models.CharField(default="Iniciar Sesión", max_length=255),
        ),
    ]
