# Generated by Django 5.0.6 on 2024-05-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_siteconfiguration_login_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="login_title_color",
            field=models.CharField(default="#FFFFFF", max_length=150),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="login_title_size",
            field=models.CharField(default="24px", max_length=150),
        ),
    ]
