# Generated by Django 5.0.6 on 2024-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_siteconfiguration_login_title_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="login_title_size",
            field=models.CharField(default="24", max_length=150),
        ),
    ]
