# Generated by Django 5.0.2 on 2024-02-21 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_securityweaponaccreditation_accreditation_and_more'),
        ('positions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='authorized_by',
            field=models.CharField(max_length=150, verbose_name='Autorizado por'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='birthday',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='birthplace',
            field=models.CharField(max_length=250, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='blood_type',
            field=models.CharField(max_length=150, verbose_name='Tipo de Sangre'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='national_forms', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='institution',
            field=models.CharField(max_length=150, verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='passport_id',
            field=models.CharField(max_length=100, verbose_name='Cédula /Pasaporte'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='phone_number',
            field=models.CharField(max_length=150, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Teléfono 2'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='national_forms', to='positions.position', verbose_name='Cargo en el Evento'),
        ),
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='type',
            field=models.CharField(choices=[('coordinación_general', 'Coordinación General'), ('protocolo', 'Protocolo'), ('seguridad', 'Seguridad'), ('personal_técnico', 'Personal Técnico'), ('Delegación Oficial', 'Delegación Oficial'), ('enlace', 'Enlace'), ('proveedor', 'Proveedor'), ('comisión_de_prensa', 'Comisión de Prensa'), ('prensa_comercial', 'Prensa Comercial')], max_length=150, verbose_name='Tipo de Acreditación'),
        ),
    ]
