# Generated by Django 5.0.1 on 2024-02-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_securityaccreditation_communication_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="WeaponType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="securityaccreditation",
            name="communication_type",
        ),
        migrations.RemoveField(
            model_name="securityaccreditation",
            name="weapon_type",
        ),
        migrations.AddField(
            model_name="securityaccreditation",
            name="communication_type",
            field=models.ManyToManyField(
                blank=True,
                related_name="security_accreditation",
                to="core.communicationtype",
            ),
        ),
        migrations.AddField(
            model_name="securityaccreditation",
            name="weapon_type",
            field=models.ManyToManyField(
                blank=True, related_name="security_accreditation", to="core.weapontype"
            ),
        ),
    ]
