# Generated by Django 5.0.1 on 2024-02-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_communicationtype_weapontype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="vehicle_type",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.ManyToManyField(
                blank=True, related_name="vehicle", to="core.vehicletypes"
            ),
        ),
    ]
