# Generated by Django 5.0.2 on 2024-02-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_nationalaccreditation_authorized_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=150, verbose_name='Tipo de Sangre'),
        ),
    ]
