# Generated by Django 5.0.6 on 2024-05-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_siteconfiguration_login_title_3"),
    ]

    operations = [
        migrations.CreateModel(
            name="PowerBiToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField()),
                ("expiration_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="ReportId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("report_id", models.CharField(max_length=255)),
            ],
        ),
    ]
