# Generated by Django 5.0.6 on 2024-05-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_powerbitoken_reportid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("report_id", models.CharField(max_length=255)),
                ("dataset_id", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="ReportId",
        ),
    ]
