# Generated by Django 5.0.2 on 2024-02-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_internationalaccreditation_medication_1_and_more'),
        ('core', '0011_alter_nationalaccreditation_blood_type'),
    ]

    operations = [
    ]
