# Generated by Django 5.0.6 on 2024-05-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_report_delete_reportid'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerbitoken',
            name='access_token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
