# Generated by Django 5.0.6 on 2024-06-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0013_powerbitoken_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="can_view",
            field=models.ManyToManyField(related_name="can_view", to="auth.group"),
        ),
    ]
