# Generated by Django 5.0 on 2024-02-23 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('positions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverflightNonCommercialAircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('jurisdiction', models.CharField(choices=[('civil', 'Civil'), ('military', 'Militar')], default='civil', max_length=50)),
                ('registration', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=150)),
                ('call_sign', models.CharField(max_length=150)),
                ('commander_name', models.CharField(max_length=150)),
                ('crew_members_count', models.IntegerField()),
                ('pmi_name', models.CharField(max_length=150)),
                ('passengers_count', models.IntegerField()),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('overflight_info', models.TextField()),
                ('landing_info', models.TextField()),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('route', models.CharField(max_length=150)),
                ('ground_facilities', models.TextField()),
                ('date', models.DateField()),
                ('signature', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_forms', to='countries.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_forms', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_forms', to='positions.position')),
                ('sub_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight_forms', to='positions.subposition')),
            ],
        ),
    ]
