# Generated by Django 5.0.1 on 2024-02-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overflight_non_commercial_aircraft", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="overflightnoncommercialaircraft",
            name="signature",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
