# Generated by Django 5.0.1 on 2024-02-29 23:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "overflight_non_commercial_aircraft",
            "0002_alter_overflightnoncommercialaircraft_signature",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="overflightnoncommercialaircraft",
            name="signature",
        ),
    ]
