# Generated by Django 5.0 on 2024-03-13 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflight_non_commercial_aircraft', '0005_overflightnoncommercialaircraft_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='overflightnoncommercialaircraft',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overflight_aircraft_authorized_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overflightnoncommercialaircraft',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overflight_aircraft_rejected_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overflightnoncommercialaircraft',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overflight_aircraft_reviewed_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
