# Generated by Django 5.0 on 2024-03-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overflight_non_commercial_aircraft', '0006_overflightnoncommercialaircraft_authorized_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overflightnoncommercialaircraft',
            old_name='jurisdiction',
            new_name='flight_type',
        ),
    ]
