# Generated by Django 5.0.2 on 2024-03-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflight_non_commercial_aircraft', '0008_overflightnoncommercialaircraft_fbo_attendant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overflightnoncommercialaircraft',
            name='flight_type',
            field=models.CharField(choices=[('CIVIL', 'Civil'), ('MILITARY', 'Militar'), ('EMERGENCY', 'Emergencia'), ('AMBULANCE', 'Ambulancia'), ('CHARTER', 'Charter'), ('OVERFLIGHT', 'Sobrevuelo'), ('TECHNICAL_SCALE', 'Escala Técnica')], default='CIVIL', max_length=50),
        ),
    ]
