# Generated by Django 5.0.6 on 2024-05-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "overflight_non_commercial_aircraft",
            "0012_alter_overflightnoncommercialaircraft_status",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="overflightnoncommercialaircraft",
            name="aircraft_type",
            field=models.CharField(
                choices=[
                    ("CIVIL", "Civil"),
                    ("MILITARY", "Militar"),
                    ("EMERGENCY", "Emergencia"),
                    ("AMBULANCE", "Ambulancia"),
                    ("CHARTER", "Charter"),
                    ("OVERFLIGHT", "Sobrevuelo"),
                    ("TECHNICAL_SCALE", "Escala Técnica"),
                ],
                default="CIVIL",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="overflightnoncommercialaircraft",
            name="flight_type",
            field=models.CharField(
                choices=[("FLIGHT", "Vuelo"), ("OVERFLIGHT", "Sobrevuelo")],
                default="FLIGHT",
                max_length=50,
            ),
        ),
    ]
