# Generated by Django 5.0.6 on 2024-05-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "overflight_non_commercial_aircraft",
            "0013_alter_overflightnoncommercialaircraft_aircraft_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="overflightnoncommercialaircraft",
            name="category",
            field=models.CharField(
                choices=[
                    ("TECHNICIANS", "Técnicos"),
                    ("DIPLOMATS", "Diplomáticos"),
                    ("MILITARIES", "Militares"),
                    ("VOLUNTEERS", "Voluntarios"),
                    ("RESCUERS", "Rescatistas"),
                ],
                default="TECHNICIANS",
                max_length=150,
            ),
        ),
    ]
