# Generated by Django 5.0.6 on 2024-05-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "overflight_non_commercial_aircraft",
            "0014_overflightnoncommercialaircraft_category",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="overflightnoncommercialaircraft",
            name="departure_date",
            field=models.DateTimeField(),
        ),
    ]
