# Generated by Django 5.0.6 on 2024-05-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "overflight_non_commercial_aircraft",
            "0015_alter_overflightnoncommercialaircraft_departure_date",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="overflightnoncommercialaircraft",
            name="arrival_date",
            field=models.DateTimeField(),
        ),
    ]
