# Generated by Django 5.0.2 on 2024-04-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='sub_positions',
            field=models.ManyToManyField(blank=True, related_name='positions', to='positions.subposition'),
        ),
    ]
