# Generated by Django 5.0.2 on 2024-02-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_remove_subposition_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='sub_positions',
            field=models.ManyToManyField(related_name='positions', to='positions.subposition'),
        ),
    ]
