# Generated by Django 5.0.2 on 2024-04-27 01:44

import commerce.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('passport_id', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('admin_name', models.CharField(blank=True, max_length=150)),
                ('admin_phone_number', models.CharField(blank=True, max_length=150)),
                ('commerce_type', models.CharField(max_length=150)),
                ('commerce_type_other', models.CharField(blank=True, max_length=150)),
                ('has_vehicle', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(blank=True, max_length=150)),
                ('vehicle_type_other', models.CharField(blank=True, max_length=150)),
                ('vehicle_plate', models.CharField(blank=True, max_length=150)),
                ('vehicle_color', models.CharField(blank=True, max_length=150)),
                ('vehicle_year', models.CharField(blank=True, max_length=150)),
                ('vehicle_model', models.CharField(blank=True, max_length=150)),
                ('downloaded', models.BooleanField(default=False)),
                ('reviewed_comment', models.TextField(blank=True)),
                ('authorized_comment', models.TextField(blank=True)),
                ('status', models.CharField(
                    choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'),
                             ('REJECTED', 'Rejected')], default='PENDING', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.TextField(blank=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='temp/q_codes/')),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                    related_name='commerce_authorized_set',
                                                    to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries.country')),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_created_set',
                                   to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                  related_name='commerce_rejected_set', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                  related_name='commerce_reviewed_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
