# Generated by Django 5.0.2 on 2024-05-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_commerceemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerce',
            name='commercial_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commerce',
            name='company_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
