# Generated by Django 5.0.2 on 2024-05-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_commerce_commercial_name_commerce_company_name'),
        ('vehicles', '0007_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerce',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='vehicles.vehicle'),
        ),
    ]
