# Generated by Django 5.0.2 on 2024-05-13 03:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_commerce_vehicles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commerce',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='commerce',
            name='authorized_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commerce',
            name='certificated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commerce',
            name='certification',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/img/'),
        ),
        migrations.AddField(
            model_name='commerce',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commerce',
            name='reviewed_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commerce',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('REVIEWED', 'Revisado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=150),
        ),
        migrations.AddField(
            model_name='commerce',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commerce',
            name='uuid',
            field=models.TextField(blank=True),
        ),
    ]
