# Generated by Django 5.0.2 on 2024-05-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_alter_commerce_options_commerce_authorized_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerceemployee',
            name='schedule',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
