# Generated by Django 5.0.6 on 2024-05-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0008_commerceemployee_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="commerce",
            name="times_edited",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
