# Generated by Django 5.0 on 2024-03-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_accreditation', '0002_alter_nationalaccreditation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalaccreditation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=150, verbose_name='Estado'),
        ),
    ]
