# Generated by Django 5.0.2 on 2024-03-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_accreditation', '0003_nationalaccreditation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=150, verbose_name='Estado'),
        ),
    ]
