# Generated by Django 5.0.2 on 2024-03-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_accreditation', '0004_alter_nationalaccreditation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('REVIEWED', 'Revisado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=150, verbose_name='Estado'),
        ),
    ]
