# Generated by Django 5.0 on 2024-03-06 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_accreditation', '0006_alter_nationalaccreditation_status'),
        ('security_accreditations', '0002_weapon_remove_securityweaponaccreditation_ammunition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalaccreditation',
            name='security_weapon_accreditation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='national_forms', to='security_accreditations.securityweaponaccreditation'),
        ),
    ]
