# Generated by Django 5.0 on 2024-03-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_accreditation', '0010_alter_nationalaccreditation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='type',
            field=models.CharField(blank=True, choices=[('GENERAL_COORDINATION', 'Coordinación General'), ('PROTOCOL', 'Protocolo'), ('SECURITY', 'Seguridad'), ('TECHNICAL_STAFF', 'Personal Técnico'), ('OFFICIAL_DELEGATION', 'Delegación Oficial'), ('LINK', 'Enlace'), ('SUPPLIER', 'Proveedor'), ('NEWSLETTER_COMMITTEE', 'Comisión de Prensa'), ('COMMERCIAL_NEWSLETTER', 'Prensa Comercial')], max_length=150, null=True),
        ),
    ]
