# Generated by Django 5.0 on 2024-03-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_accreditation', '0011_alter_nationalaccreditation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalaccreditation',
            name='private_insurance',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
