# Generated by Django 5.0.2 on 2024-03-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_accreditation', '0012_nationalaccreditation_private_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalaccreditation',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
