# Generated by Django 5.0.2 on 2024-03-19 04:22

import national_accreditation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_accreditation', '0014_nationalaccreditation_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalaccreditation',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=national_accreditation.models.qr_filename),
        ),
    ]
