# Generated by Django 5.0.2 on 2024-03-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_accreditation', '0015_nationalaccreditation_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalaccreditation',
            name='authorized_comment',
            field=models.TextField(blank=True),
        ),
    ]
