# Generated by Django 5.0 on 2024-04-17 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0001_initial"),
        ("national_accreditation", "0019_nationalaccreditation_allergies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nationalaccreditation",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="countries.country",
            ),
            preserve_default=False,
        ),
    ]
