# Generated by Django 5.0.6 on 2024-05-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("national_accreditation", "0022_alter_nationalaccreditation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="nationalaccreditation",
            name="times_updated",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
