# Generated by Django 5.0.6 on 2024-05-16 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("national_accreditation", "0023_nationalaccreditation_times_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nationalaccreditation",
            old_name="times_updated",
            new_name="times_edited",
        ),
    ]
