# Generated by Django 5.0.2 on 2024-05-31 01:43

import national_accreditation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_accreditation', '0025_alter_nationalaccreditation_allergies_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalaccreditation',
            name='passport_id_image',
            field=models.ImageField(blank=True, null=True, upload_to=national_accreditation.models.passport_image_filename),
        ),
    ]
