# Generated by Django 5.0.6 on 2024-06-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_accreditation', '0027_alter_nationalaccreditation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalaccreditation',
            name='type',
            field=models.CharField(blank=True, choices=[('GENERAL_COORDINATION', 'Coordinación General'), ('PROTOCOL', 'Protocolo'), ('SECURITY', 'Seguridad'), ('TECHNICAL_STAFF', 'Personal Técnico'), ('OFFICIAL_DELEGATION', 'Delegación Oficial'), ('LINK', 'Enlace'), ('SUPPLIER', 'Proveedor'), ('NEWSLETTER_COMMITTEE', 'Comisión de Prensa'), ('COMMERCIAL_NEWSLETTER', 'Prensa Comercial'), ('OFFICIAL_NEWSLETTER', 'Prensa Oficial'), ('TRANSPORT', 'Transporte'), ('BILATERAL_TECHNICAL', 'Técnico Bilateral')], max_length=150, null=True),
        ),
    ]
