# Generated by Django 5.0 on 2024-03-06 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_accreditations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=150, verbose_name='Arma')),
                ('brand', models.CharField(max_length=150, verbose_name='Marca')),
                ('model', models.CharField(max_length=150, verbose_name='Modelo')),
                ('type', models.CharField(max_length=150, verbose_name='Tipo de Arma')),
                ('serial', models.CharField(max_length=150, verbose_name='Serial No.')),
                ('caliber', models.CharField(max_length=150, verbose_name='Calibre')),
                ('chargers', models.IntegerField(verbose_name='Cantidad de Cargadores')),
                ('ammunition', models.IntegerField(verbose_name='Total de Municiones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='securityweaponaccreditation',
            name='ammunition',
        ),
        migrations.RemoveField(
            model_name='securityweaponaccreditation',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='securityweaponaccreditation',
            name='caliber',
        ),
        migrations.RemoveField(
            model_name='securityweaponaccreditation',
            name='chargers',
        ),
        migrations.RemoveField(
            model_name='securityweaponaccreditation',
            name='control_date',
        ),
        migrations.RemoveField(
            model_name='securityweaponaccreditation',
            name='control_time',
        ),
        migrations.RemoveField(
            model_name='securityweaponaccreditation',
            name='model',
        ),
        migrations.RemoveField(
            model_name='securityweaponaccreditation',
            name='serial',
        ),
        migrations.RemoveField(
            model_name='securityweaponaccreditation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='securityweaponaccreditation',
            name='weapon',
        ),
        migrations.AddField(
            model_name='securityweaponaccreditation',
            name='control_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 4, 31, 20, 736913, tzinfo=datetime.timezone.utc), verbose_name='Fecha y hora de Control'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityweaponaccreditation',
            name='weapons',
            field=models.ManyToManyField(blank=True, related_name='security_weapons', to='security_accreditations.weapon'),
        ),
    ]
