# Generated by Django 5.0.1 on 2024-03-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "security_accreditations",
            "0002_weapon_remove_securityweaponaccreditation_ammunition_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("REVIEWED", "Revisado"),
                    ("APPROVED", "Aprobado"),
                    ("REJECTED", "Rechazado"),
                ],
                default="PENDING",
                max_length=150,
            ),
        ),
    ]
