# Generated by Django 5.0.3 on 2024-03-19 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0001_initial"),
        ("positions", "0001_initial"),
        (
            "security_accreditations",
            "0004_securityweaponaccreditation_authorized_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="airportArrival",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="airportDeparture",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_accreditations",
                to="countries.country",
            ),
        ),
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="dateArrival",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="dateDeparture",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="flightNumberArrival",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="flightNumberDeparture",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="hourArrival",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="hourDeparture",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="passportNo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="security_accreditations",
                to="positions.position",
            ),
        ),
    ]
