# Generated by Django 5.0.3 on 2024-03-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "security_accreditations",
            "0006_alter_securityweaponaccreditation_country_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="securityweaponaccreditation",
            old_name="airportArrival",
            new_name="flight_arrival_airport",
        ),
        migrations.RenameField(
            model_name="securityweaponaccreditation",
            old_name="airportDeparture",
            new_name="flight_arrival_number",
        ),
        migrations.RenameField(
            model_name="securityweaponaccreditation",
            old_name="flightNumberArrival",
            new_name="flight_departure_airport",
        ),
        migrations.RenameField(
            model_name="securityweaponaccreditation",
            old_name="flightNumberDeparture",
            new_name="flight_departure_number",
        ),
        migrations.RenameField(
            model_name="securityweaponaccreditation",
            old_name="passportNo",
            new_name="passport_id",
        ),
        migrations.RemoveField(
            model_name="securityweaponaccreditation",
            name="dateArrival",
        ),
        migrations.RemoveField(
            model_name="securityweaponaccreditation",
            name="dateDeparture",
        ),
        migrations.RemoveField(
            model_name="securityweaponaccreditation",
            name="hourArrival",
        ),
        migrations.RemoveField(
            model_name="securityweaponaccreditation",
            name="hourDeparture",
        ),
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="flight_arrival_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityweaponaccreditation",
            name="flight_departure_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
