# Generated by Django 5.0.3 on 2024-03-19 05:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "security_accreditations",
            "0007_rename_airportarrival_securityweaponaccreditation_flight_arrival_airport_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="securityweaponaccreditation",
            old_name="flight_arrival_number",
            new_name="flight_number_arrival",
        ),
        migrations.RenameField(
            model_name="securityweaponaccreditation",
            old_name="flight_departure_number",
            new_name="flight_number_departure",
        ),
    ]
