# Generated by Django 5.0.2 on 2024-03-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security_accreditations', '0008_rename_flight_arrival_number_securityweaponaccreditation_flight_number_arrival_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityweaponaccreditation',
            old_name='flight_number_arrival',
            new_name='flight_arrival_number',
        ),
        migrations.RenameField(
            model_name='securityweaponaccreditation',
            old_name='flight_number_departure',
            new_name='flight_departure_number',
        ),
    ]
