# Generated by Django 5.0 on 2024-03-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_accreditations', '0009_rename_flight_number_arrival_securityweaponaccreditation_flight_arrival_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityweaponaccreditation',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
