# Generated by Django 5.0.2 on 2024-03-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_accreditations', '0010_securityweaponaccreditation_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityweaponaccreditation',
            name='permit_number',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='caliber',
            field=models.CharField(blank=True, default='9mm', max_length=150),
        ),
    ]
