# Generated by Django 5.0.2 on 2024-04-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_accreditations', '0011_securityweaponaccreditation_permit_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityweaponaccreditation',
            name='reviewed_comment',
            field=models.TextField(blank=True),
        ),
    ]
