# Generated by Django 5.0 on 2024-02-29 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAccessAirportAccreditations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_responsible', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_access_airport_accreditations', to='countries.country')),
                ('vehicles', models.ManyToManyField(related_name='vehicle_access_airport_accreditations', to='vehicles.vehicle')),
            ],
        ),
    ]
