# Generated by Django 5.0 on 2024-03-13 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_access_airport_accreditations', '0003_vehicleaccessairportaccreditations_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleaccessairportaccreditations',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_airport_access_authorized_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleaccessairportaccreditations',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_airport_access_rejected_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleaccessairportaccreditations',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_airport_access_reviewed_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
