# Generated by Django 5.0.2 on 2024-04-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_access_airport_accreditations', '0004_vehicleaccessairportaccreditations_authorized_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleaccessairportaccreditations',
            name='reviewed_comment',
            field=models.TextField(blank=True),
        ),
    ]
