# Generated by Django 5.0.6 on 2024-06-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vehicle_access_airport_accreditations",
            "0007_alter_vehicleaccessairportaccreditations_status",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicleaccessairportaccreditations",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="vehicleaccessairportaccreditations",
            name="authorized_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleaccessairportaccreditations",
            name="certificated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicleaccessairportaccreditations",
            name="certification",
            field=models.ImageField(
                blank=True, null=True, upload_to="certifications/img/"
            ),
        ),
        migrations.AddField(
            model_name="vehicleaccessairportaccreditations",
            name="uuid",
            field=models.TextField(blank=True),
        ),
    ]
