# Generated by Django 5.0.6 on 2024-06-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vehicle_access_airport_accreditations",
            "0008_alter_vehicleaccessairportaccreditations_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicleaccessairportaccreditations",
            options={},
        ),
        migrations.AlterField(
            model_name="vehicleaccessairportaccreditations",
            name="certification",
            field=models.FileField(
                blank=True, null=True, upload_to="certifications/pdf/"
            ),
        ),
        migrations.AlterField(
            model_name="vehicleaccessairportaccreditations",
            name="reviewed_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
