# Generated by Django 5.0.6 on 2024-06-06 01:45

import vehicle_access_airport_accreditations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vehicle_access_airport_accreditations",
            "0009_alter_vehicleaccessairportaccreditations_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleaccessairportaccreditations",
            name="certification",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=vehicle_access_airport_accreditations.models.get_information_responsible,
            ),
        ),
    ]
