# Generated by Django 5.0 on 2024-03-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=15, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
