# Generated by Django 5.0 on 2024-02-23 03:08

import django.db.models.deletion
import international_accreditation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allergies', '0001_initial'),
        ('countries', '0001_initial'),
        ('immunizations', '0001_initial'),
        ('media_channels', '0001_initial'),
        ('medical_histories', '0001_initial'),
        ('positions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=international_accreditation.models.image_filename)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('passport_id', models.CharField(max_length=150)),
                ('authorization_letter', models.FileField(blank=True, upload_to=international_accreditation.models.authorization_letter_filename)),
                ('institution', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=150)),
                ('phone_number_2', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField()),
                ('birthplace', models.CharField(max_length=150)),
                ('blood_group', models.CharField(blank=True, max_length=150)),
                ('blood_rh_factor', models.CharField(blank=True, max_length=150)),
                ('age', models.PositiveIntegerField(default=18)),
                ('diseases', models.TextField()),
                ('medication_1', models.CharField(blank=True, max_length=200)),
                ('medication_2', models.CharField(blank=True, max_length=200)),
                ('medication_3', models.CharField(blank=True, max_length=200)),
                ('medication_4', models.CharField(blank=True, max_length=200)),
                ('surgical', models.CharField(blank=True, max_length=150)),
                ('doctor_name', models.CharField(blank=True, max_length=100)),
                ('hotel_name', models.CharField(max_length=120)),
                ('hotel_address', models.CharField(max_length=120)),
                ('hotel_phone', models.CharField(max_length=120)),
                ('flight_arrival_date', models.DateField()),
                ('flight_arrival_time', models.TimeField()),
                ('flight_arrival_number', models.CharField(max_length=150)),
                ('flight_departure_date', models.DateField()),
                ('flight_departure_time', models.TimeField()),
                ('flight_departure_number', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('jefe_de_delegación_oficial', 'Jefe de Delegación Oficial'), ('delegación_oficial', 'Delegación Oficial'), ('protocolo', 'Protocolo'), ('seguridad', 'Seguridad'), ('personal_de_apoyo', 'Personal de Apoyo'), ('prensa_oficial', 'Prensa Oficial'), ('tripulación', 'Tripulación'), ('prensa_comercial', 'Prensa Comercial')], max_length=150)),
                ('authorized_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergies', models.ManyToManyField(blank=True, related_name='international_forms', to='allergies.allergy')),
                ('authorized_by_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='positions.position')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='international_forms', to='countries.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='international_forms', to=settings.AUTH_USER_MODEL)),
                ('flight_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_from', to='countries.country')),
                ('flight_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_to', to='countries.country')),
                ('immunizations', models.ManyToManyField(blank=True, related_name='international_forms', to='immunizations.immunization')),
                ('media_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='international_forms', to='media_channels.mediachannel')),
                ('medicals', models.ManyToManyField(blank=True, related_name='international_forms', to='medical_histories.medicalhistory')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='international_forms', to='positions.position')),
                ('sub_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='international_forms', to='positions.subposition')),
            ],
        ),
    ]
