# Generated by Django 5.0.2 on 2024-02-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("international_accreditation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internationalaccreditation",
            name="type",
            field=models.CharField(
                choices=[
                    ("jefe_de_delegación_oficial", "Official Delegation Head"),
                    ("delegación_oficial", "Delegación Oficial"),
                    ("protocolo", "Protocolo"),
                    ("seguridad", "Seguridad"),
                    ("personal_de_apoyo", "Personal de Apoyo"),
                    ("prensa_oficial", "Prensa Oficial"),
                    ("tripulación", "Tripulación"),
                    ("prensa_comercial", "Prensa Comercial"),
                ],
                max_length=150,
                verbose_name="Tipo de Acreditación",
            ),
        ),
    ]
