# Generated by Django 5.0.1 on 2024-03-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("allergies", "0001_initial"),
        ("immunizations", "0001_initial"),
        ("international_accreditation", "0002_alter_internationalaccreditation_type"),
        ("medical_histories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internationalaccreditation",
            name="allergies",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="international_forms",
                to="allergies.allergy",
            ),
        ),
        migrations.AlterField(
            model_name="internationalaccreditation",
            name="immunizations",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="international_forms",
                to="immunizations.immunization",
            ),
        ),
        migrations.AlterField(
            model_name="internationalaccreditation",
            name="medicals",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="international_forms",
                to="medical_histories.medicalhistory",
            ),
        ),
    ]
