# Generated by Django 5.0 on 2024-03-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0006_alter_internationalaccreditation_phone_number_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalaccreditation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=150, verbose_name='Estado'),
        ),
    ]
