# Generated by Django 5.0 on 2024-03-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0010_alter_internationalaccreditation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalaccreditation',
            name='type',
            field=models.CharField(blank=True, choices=[('OFFICIAL_DELEGATION_HEAD', 'Official Delegation Head'), ('OFFICIAL_DELEGATION', 'Delegación Oficial'), ('PROTOCOL', 'Protocolo'), ('SECURITY', 'Seguridad'), ('SUPPORT_STAFF', 'Personal de Apoyo'), ('OFFICIAL_NEWSLETTER', 'Prensa Oficial'), ('CREW', 'Tripulación'), ('COMMERCIAL_NEWSLETTER', 'Prensa Comercial')], max_length=150, null=True, verbose_name='Tipo de Acreditación'),
        ),
    ]
