# Generated by Django 5.0 on 2024-03-06 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0011_alter_internationalaccreditation_type'),
        ('security_accreditations', '0002_weapon_remove_securityweaponaccreditation_ammunition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalaccreditation',
            name='security_weapon_accreditation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='international_forms', to='security_accreditations.securityweaponaccreditation'),
        ),
    ]
