# Generated by Django 5.0.2 on 2024-03-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0012_internationalaccreditation_security_weapon_accreditation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationalaccreditation',
            name='authorized_by',
        ),
        migrations.RemoveField(
            model_name='internationalaccreditation',
            name='authorized_by_position',
        ),
    ]
