# Generated by Django 5.0 on 2024-03-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0015_alter_internationalaccreditation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internationalaccreditation',
            name='blood_rh_factor',
        ),
    ]
