# Generated by Django 5.0 on 2024-03-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0017_internationalaccreditation_private_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalaccreditation',
            name='allergies_description',
            field=models.TextField(blank=True),
        ),
    ]
