# Generated by Django 5.0.2 on 2024-03-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0018_internationalaccreditation_allergies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalaccreditation',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
