# Generated by Django 5.0.2 on 2024-03-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0019_internationalaccreditation_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalaccreditation',
            name='uuid',
            field=models.TextField(blank=True),
        ),
    ]
