# Generated by Django 5.0.2 on 2024-03-19 04:22

import international_accreditation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0020_internationalaccreditation_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalaccreditation',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=international_accreditation.models.qr_filename),
        ),
    ]
