# Generated by Django 5.0.2 on 2024-04-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0022_internationalaccreditation_authorized_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalaccreditation',
            name='reviewed_comment',
            field=models.TextField(blank=True),
        ),
    ]
