# Generated by Django 5.0.2 on 2024-05-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0024_alter_internationalaccreditation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internationalaccreditation',
            old_name='downloaded',
            new_name='certificated',
        ),
        migrations.RenameField(
            model_name='internationalaccreditation',
            old_name='qr_code',
            new_name='certification',
        ),
    ]
