# Generated by Django 5.0.6 on 2024-05-09 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0001_initial"),
        (
            "international_accreditation",
            "0025_rename_downloaded_internationalaccreditation_certificated_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="internationalaccreditation",
            name="flight_arrival_datetime",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="internationalaccreditation",
            name="flight_arrival_number",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="internationalaccreditation",
            name="flight_departure_datetime",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="internationalaccreditation",
            name="flight_departure_number",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="internationalaccreditation",
            name="flight_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flight_from",
                to="countries.country",
            ),
        ),
        migrations.AlterField(
            model_name="internationalaccreditation",
            name="flight_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flight_to",
                to="countries.country",
            ),
        ),
        migrations.AlterField(
            model_name="internationalaccreditation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("REVIEWED", "Revisado"),
                    ("APPROVED", "Aprobado"),
                    ("REJECTED", "Rechazado"),
                ],
                default="PENDING",
                max_length=150,
            ),
        ),
    ]
