# Generated by Django 5.0.2 on 2024-05-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0026_alter_internationalaccreditation_flight_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalaccreditation',
            name='diseases',
            field=models.TextField(blank=True),
        ),
    ]
