# Generated by Django 5.0.2 on 2024-05-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0027_alter_internationalaccreditation_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalaccreditation',
            name='flight_arrival_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internationalaccreditation',
            name='flight_departure_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
