# Generated by Django 5.0.2 on 2024-05-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0028_alter_internationalaccreditation_flight_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalaccreditation',
            name='flight_arrival_airport',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='internationalaccreditation',
            name='flight_departure_airport',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
