# Generated by Django 5.0.2 on 2024-05-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0030_internationalaccreditation_times_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalaccreditation',
            name='allergies_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internationalaccreditation',
            name='authorized_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internationalaccreditation',
            name='reviewed_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
