# Generated by Django 5.0.2 on 2024-05-31 00:15

import international_accreditation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international_accreditation', '0031_alter_internationalaccreditation_allergies_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalaccreditation',
            name='passport_id_image',
            field=models.ImageField(blank=True, null=True, upload_to=international_accreditation.models.passport_image_filename),
        ),
    ]
