# Generated by Django 5.0 on 2024-02-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=150)),
                ('color', models.CharField(max_length=150)),
                ('plate', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=150)),
                ('driver_id', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
