# Generated by Django 5.0 on 2024-03-18 04:46

import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_license',
            field=models.FileField(blank=True, null=True, upload_to=vehicles.models.driver_license_filename),
        ),
    ]
