# Generated by Django 5.0.2 on 2024-04-17 20:27

import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_driver_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='circulation_card',
            field=models.FileField(blank=True, null=True, upload_to=vehicles.models.driver_license_filename),
        ),
    ]
