# Generated by Django 5.0.2 on 2024-04-17 20:29

import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vehicles', '0003_vehicle_circulation_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='circulation_card',
            field=models.FileField(blank=True, null=True, upload_to=vehicles.models.tpv_filename),
        ),
    ]
