# Generated by Django 5.0.2 on 2024-04-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_rename_circulation_card_vehicle_tpv'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='type_other',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
