# Generated by Django 5.0 on 2024-03-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_vehicle_accreditation', '0002_generalvehicleaccreditation_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalvehicleaccreditation',
            old_name='assigned_by',
            new_name='assigned_to',
        ),
    ]
