# Generated by Django 5.0.1 on 2024-03-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "general_vehicle_accreditation",
            "0003_rename_assigned_by_generalvehicleaccreditation_assigned_to",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generalvehicleaccreditation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("REVIEWED", "Revisado"),
                    ("APPROVED", "Aprobado"),
                    ("REJECTED", "Rechazado"),
                ],
                default="PENDING",
                max_length=150,
            ),
        ),
    ]
