# Generated by Django 5.0.2 on 2024-04-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_vehicle_accreditation', '0005_generalvehicleaccreditation_authorized_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalvehicleaccreditation',
            name='reviewed_comment',
            field=models.TextField(blank=True),
        ),
    ]
