# Generated by Django 5.0.2 on 2024-04-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_vehicle_accreditation', '0007_alter_generalvehicleaccreditation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalvehicleaccreditation',
            name='mission',
        ),
        migrations.AddField(
            model_name='generalvehicleaccreditation',
            name='accreditation_type',
            field=models.CharField(choices=[('OFFICIAL_NEWSLETTER', 'Prensa Oficial'), ('COMMERCIAL_NEWSLETTER', 'Prensa Nacional'), ('INTERNATIONAL_NEWSLETTER', 'Prensa Internacional'), ('DIPLOMATIC_MISSION', 'Misión Diplomática')], default='DIPLOMATIC_MISSION', max_length=150),
        ),
        migrations.AddField(
            model_name='generalvehicleaccreditation',
            name='country',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
