# Generated by Django 5.0.2 on 2024-05-10 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_vehicle_accreditation', '0009_alter_generalvehicleaccreditation_status'),
        ('vehicles', '0007_vehicle_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalvehicleaccreditation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='generalvehicleaccreditation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='generalvehicleaccreditation',
            name='vehicles',
        ),
        migrations.AddField(
            model_name='generalvehicleaccreditation',
            name='authorized_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generalvehicleaccreditation',
            name='certificated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalvehicleaccreditation',
            name='certification',
            field=models.ImageField(blank=True, upload_to='certifications/img/'),
        ),
        migrations.AddField(
            model_name='generalvehicleaccreditation',
            name='uuid',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generalvehicleaccreditation',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.vehicle'),
        ),
        migrations.AlterField(
            model_name='generalvehicleaccreditation',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_vehicle_authorized_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalvehicleaccreditation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_vehicle_created_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalvehicleaccreditation',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_vehicle_rejected_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='generalvehicleaccreditation',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_vehicle_reviewed_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
