# Generated by Django 5.0.2 on 2024-05-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_vehicle_accreditation', '0011_generalvehicleaccreditation_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalvehicleaccreditation',
            name='certification',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/img/'),
        ),
    ]
