# Generated by Django 5.0.6 on 2024-05-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "general_vehicle_accreditation",
            "0012_alter_generalvehicleaccreditation_certification",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalvehicleaccreditation",
            name="accreditation_type",
            field=models.CharField(
                choices=[
                    ("OFFICIAL_NEWSLETTER", "Prensa Oficial"),
                    ("COMMERCIAL_NEWSLETTER", "Prensa Nacional"),
                    ("INTERNATIONAL_NEWSLETTER", "Prensa Internacional"),
                    ("DIPLOMATIC_MISSION", "Misión Diplomática"),
                    ("MINREX_OFFICIALS", "Funcionarios MINREX"),
                ],
                default="DIPLOMATIC_MISSION",
                max_length=150,
            ),
        ),
    ]
