# Generated by Django 5.0.2 on 2024-05-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_vehicle_accreditation', '0013_alter_generalvehicleaccreditation_accreditation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalvehicleaccreditation',
            name='authorized_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generalvehicleaccreditation',
            name='reviewed_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
