# Generated by Django 5.0.2 on 2024-06-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_vehicle_accreditation', '0014_alter_generalvehicleaccreditation_authorized_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalvehicleaccreditation',
            name='accreditation_type_vehicle',
            field=models.CharField(choices=[('INSTITUTIONAL_SUPPORT', 'Apoyo Institucional'), ('OTHER', 'Otro')], default='INSTITUTIONAL_SUPPORT', max_length=150),
        ),
        migrations.AlterField(
            model_name='generalvehicleaccreditation',
            name='accreditation_type',
            field=models.CharField(choices=[('OFFICIAL_NEWSLETTER', 'Prensa Oficial'), ('COMMERCIAL_NEWSLETTER', 'Prensa Nacional'), ('INTERNATIONAL_NEWSLETTER', 'Prensa Internacional'), ('DIPLOMATIC_MISSION', 'Misión Diplomática'), ('MINREX_OFFICIALS', 'Funcionarios MINREX'), ('VEHICLES', 'Vehículos')], default='DIPLOMATIC_MISSION', max_length=150),
        ),
    ]
