# Generated by Django 5.0.2 on 2024-06-24 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('general_vehicle_accreditation', '0015_generalvehicleaccreditation_accreditation_type_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalvehicleaccreditation',
            name='certification_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='credentials.vehiclecertification'),
        ),
    ]
