from core.forms.communication_equipment_declaration_form import CommunicationEquipmentDeclarationForm
from core.forms.general_vehicle_accreditation_form import GeneralVehicleAccreditationForm
from core.forms.international_accreditation_form import InternationalAccreditationForm
from core.forms.medical_report_form import MedicalReportForm
from core.forms.national_accreditation_form import NationalAccreditationForm
from core.forms.newsletter_international_form import NewsletterInternationalForm
from core.forms.newsletter_national_form import NewsletterNationalForm
from core.forms.overflight_non_commercial_aircraft_form import OverflightNonCommercialAircraftForm
from core.forms.security_weapons_registration_form import SecurityWeaponAccreditationForm, SecurityWeaponFormSet
from core.forms.vehicle_access_airport_form import VehicleAccessAirportForm
