# Generated by Django 5.0.2 on 2024-04-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercom_equipment_declaration', '0005_intercomequipmentdeclaration_reviewed_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercomequipmentdeclaration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=150),
        ),
    ]
