from core.admin.communication_equipment_declaration_admin import CommunicationEquipmentDeclarationAdmin, EquipmentItemAdmin
from core.admin.general_vehicle_accreditation_admin import GeneralVehicleAccreditationAdmin
from core.admin.international_accreditation_admin import InternationalAccreditationAdmin
from core.admin.national_accreditation_admin import NationalAccreditationAdmin
from core.admin.overflight_non_commercial_aircraft_admin import OverflightNonCommercialAircraftAdmin
from core.admin.security_weapons_registration_admin import SecurityWeaponAccreditationAdmin
from core.admin.vehicle_access_airport_admin import VehicleAccessAirport
