# Generated by Django 5.0.2 on 2024-04-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='vehicle_type_other',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
