# Generated by Django 5.0.2 on 2024-05-07 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_housing_vehicle_type_other'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housing',
            options={'ordering': ['-updated_at']},
        ),
    ]
