# Generated by Django 5.0.2 on 2024-05-11 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_alter_housing_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housing',
            options={},
        ),
        migrations.RemoveField(
            model_name='housing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='authorized_comment',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='country',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='downloaded',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='email',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='has_vehicle',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='passport_id',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='reviewed_comment',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='status',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='vehicle_plate',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='vehicle_type_other',
        ),
        migrations.RemoveField(
            model_name='housing',
            name='vehicle_year',
        ),
    ]
