# Generated by Django 5.0.2 on 2024-05-11 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('housing', '0005_alter_housing_options_remove_housing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('passport_id', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='countries.country')),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='housing.housing')),
            ],
        ),
    ]
