# Generated by Django 5.0.2 on 2024-05-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_housing_vehicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingperson',
            name='address',
        ),
        migrations.AddField(
            model_name='housing',
            name='address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
