# Generated by Django 5.0.6 on 2024-05-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0009_remove_housingperson_address_housing_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="housing",
            name="times_edited",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
